---
version: '3.9'
services:
  grafana:
    image: grafana/grafana:8.1.1
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/pyroscope-io/grafana-panel-plugin/releases/download/v1.1.0/pyroscope-panel-1.1.0.zip;pyroscope-panel,https://github.com/pyroscope-io/grafana-datasource-plugin/releases/download/v1.1.0/pyroscope-datasource-1.1.0.zip;pyroscope-datasource
    ports:
      - 3000:3000

  pyroscope:
    image: 'pyroscope/pyroscope:latest'
    command:
      - server
    environment:
      - PYROSCOPE_LOG_LEVEL=info

  app:
    build: golang-example
    environment:
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
