version: '3.9'
services:
  optimized:
    environment:
      - REGION=optimized
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    build:
      context: .
      dockerfile: Dockerfile.optimized

  unoptimized:
    environment:
      - REGION=unoptimized
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040

    build:
      context: .
      dockerfile: Dockerfile.unoptimized

  pyroscope:
    image: pyroscope/pyroscope:latest
    environment:
      - PYROSCOPE_LOG_LEVEL=debug
    ports:
      - '4040:4040'
    command:
      - 'server'

  load-generator:
    build:
      context: .
      dockerfile: Dockerfile.load-generator
