remote-write:
  enabled: true
  targets:
    cloud:
      address: https://pyroscope.cloud
      # auth-token:

scrape-configs:
  - job-name: testing
    enabled-profiles: [cpu, mem]
    static-configs:
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-0
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-1
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-2
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-3
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-4
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-5
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-6
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-7
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-8
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-9
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-10
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-11
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-12
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-13
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-14
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-15
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-16
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-17
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-18
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-19
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-20
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-21
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-22
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-23
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-24
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-25
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-26
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-27
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-28
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-29
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-30
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-31
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-32
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-33
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-34
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-35
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-36
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-37
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-38
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-39
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-40
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-41
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-42
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-43
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-44
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-45
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-46
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-47
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-48
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-49
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-50
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-51
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-52
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-53
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-54
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-55
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-56
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-57
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-58
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-59
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-60
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-61
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-62
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-63
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-64
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-65
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-66
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-67
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-68
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-69
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-70
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-71
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-72
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-73
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-74
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-75
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-76
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-77
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-78
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-79
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-80
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-81
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-82
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-83
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-84
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-85
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-86
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-87
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-88
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-89
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-90
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-91
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-92
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-93
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-94
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-95
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-96
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-97
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-98
      - application: testapp
        targets:
          - localhost:4042
        labels:
          pod: pod-99
