apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fire.fullname" . }}-config
  labels:
    {{- include "fire.labels" . | nindent 4 }}
data:
  config.yaml: |

    {{ .Values.fire.config | nindent 4 }}
