{{- if .Values.fire.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fire.serviceAccountName" . }}
  labels:
    {{- include "fire.labels" . | nindent 4 }}
  {{- with .Values.fire.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
