scrape_configs:
  - job_name: "phlare"
    scrape_interval: "15s"
    static_configs:
      - targets: ["phlare:4100"]
  - job_name: "grafana"
    scrape_interval: "15s"
    static_configs:
      - targets: ["grafana:6060"]
  - job_name: "cp-rust"
    scrape_interval: "15s"
    static_configs:
      - targets: ["rust:3000"]
    profiling_config:
      pprof_config:
        block: { enabled: false }
        goroutine: { enabled: false }
        memory: { enabled: false }
        mutex: { enabled: false }
  - job_name: "cp-python"
    scrape_interval: "15s"
    static_configs:
      - targets: ["python:8081"]
    profiling_config:
      pprof_config:
        block: { enabled: false }
        goroutine: { enabled: false }
        mutex: { enabled: false }
