apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phlare.fullname" . }}-config
  labels:
    {{- include "phlare.labels" . | nindent 4 }}
data:
  config.yaml: |

    {{ .Values.phlare.config | nindent 4 }}
