version: '2.3'

services:
  web:
    build: ./app
    cap_add:
      - SYS_PTRACE
    command: /usr/bin/pyroscope exec --sample-rate=1 python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  pyroscope:
    image: pyroscope_local
    #    environment:
    #      - PYROSCOPE_LOG_LEVEL=debug
    cap_add:
      - SYS_PTRACE
    ports:
      - '4040:4040'
    command:
      - 'server'
  load-generator:
    build:
      context: .
      dockerfile: Dockerfile.load-generator

volumes:
  postgres_data:
