name: Publish Flamegraph package to npmjs

on:
  push:
    branches:
      [main, 'build/lerna-test']
      #  pull_request:
      #    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0

      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        # For PRs check the actual commit
        # https://github.com/actions/checkout/issues/124#issuecomment-586664611
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'
          registry-url: 'https://registry.npmjs.org'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - name: Install Webapp dependencies
        run: yarn bootstrap

      - name: Prepare
        id: prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          echo ::set-output name=tag::${TAG}

      - name: Build
        run: yarn build:flamegraph

      - name: Publish Pull Request
        if: github.event_name != 'pull_request'
        run: |
          yarn run lerna publish \
            --skip-git \
            --conventional-commits \
            --canary \
            --preid=${{ github.event.pull_request.number }} \
            --yes \
            --no-verify-access

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump version, generate changelog etc
        if: github.event_name != 'pull_request'
        run: |
          # Copied from https://github.com/pyroscope-io/pyroscope/blob/main/.github/workflows/update-contributors.yml#L23-L28
          git config --global user.email "dmitry+bot@pyroscope.io"
          git config --global user.name "Pyroscope Bot <dmitry+bot@pyroscope.io>"
          yarn run lerna version --conventional-commits --yes
          #        if: ${{ github.ref == 'refs/heads/main' }}
      - name: Publish Main
        if: github.event_name != 'pull_request'
        run:
          yarn run lerna publish \
          --skip-git \
          --conventional-commits \
          --yes \
          --no-verify-access
          #        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
