name: Publish Package to npmjs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        # For PRs check the actual commit
        # https://github.com/actions/checkout/issues/124#issuecomment-586664611
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'
          registry-url: 'https://registry.npmjs.org'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - name: Install Webapp dependencies
        run: yarn bootstrap

      - name: Prepare
        id: prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          echo ::set-output name=tag::${TAG}

      - name: Build
        run: PYROSCOPE_LIB_VERSION=${{ steps.prep.outputs.tag }} yarn build:flamegraph

      - name: Publish (dry-run)
        run: npm publish packages/pyroscope-flamegraph --tag=beta --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # TODO: use lerna publish
      - name: Publish (dry-run)
        #        run: npm publish packages/flamegraph/dist --tag=beta --dry-run
        run: |
          #yarn config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          # use npm to publish?
          #          sed -i 's/yarn/npm/' lerna.json
          ./node_modules/.bin/lerna publish \
            --skip-git \
            --conventional-commits \
            --canary \
            --preid=${{ github.event.pull_request.number }} \
            --yes \
            --no-verify-access

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: npm publish packages/flamegraph/dist --tag=beta
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
