name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache go mod directories
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Ensure logrus is not used by pkg/agent/profiler
        run: make ensure-logrus-not-used
      - name: Run Go tests
        run: go test -tags debugspy -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Install Webapp dependencies
        run: yarn install
      - name: Run Webapp tests
        run: yarn run test
      - name: Run Webapp lints
        run: yarn lint
      - name: Upload codecov coverage
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
          verbose: true
