name: Upload test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/flamegraph.com
        id: upload
        with:
          file: tests.pb.gz
      - name: Get Uploaded file
        run: echo "${{ steps.upload.outputs.url }}"
