name: Upload test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'
      - run: go test -cpuprofile=tests.cpu -memprofile=tests.mem ./pkg/admin
      - uses: ./.github/actions/flamegraph.com
        id: upload
        with:
          file: tests.cpu
      - uses: ./.github/actions/flamegraph.com
        id: upload2
        with:
          file: tests.mem
      - name: Get Uploaded file
        run: echo "${{ steps.upload.outputs.url }}"
