name: Windows build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-tests:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: true
      matrix:
        os: [windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build . -f Dockerfile.windows
